// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0hC5FnX6WuWR76D_Ip_K9KcfI1qWP-os',
    appId: '1:970785913227:web:1e97c776179d75a150d78e',
    messagingSenderId: '970785913227',
    projectId: 'flutter-sign-in-4d48d',
    authDomain: 'flutter-sign-in-4d48d.firebaseapp.com',
    storageBucket: 'flutter-sign-in-4d48d.appspot.com',
    measurementId: 'G-57B2BEFE14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq9Ls_w1aIYK2arfdwMGPaW8X4HRpdt6I',
    appId: '1:970785913227:android:460e661e0a88fe5250d78e',
    messagingSenderId: '970785913227',
    projectId: 'flutter-sign-in-4d48d',
    storageBucket: 'flutter-sign-in-4d48d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwdS8LCYAlhv7n4eJoal8ay3vH9TsLcwA',
    appId: '1:970785913227:ios:d04b25cefeb34cab50d78e',
    messagingSenderId: '970785913227',
    projectId: 'flutter-sign-in-4d48d',
    storageBucket: 'flutter-sign-in-4d48d.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwdS8LCYAlhv7n4eJoal8ay3vH9TsLcwA',
    appId: '1:970785913227:ios:849d1bfc115f3ea850d78e',
    messagingSenderId: '970785913227',
    projectId: 'flutter-sign-in-4d48d',
    storageBucket: 'flutter-sign-in-4d48d.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
